/**
 * Dental Appointment Calendar - Payment Form Template
 * Contains the payment form HTML generator
 */

/**
 * Generate Payment Form HTML
 * @param {string} lang - Current language ('en' or 'kh')
 * @param {Array} patients - Array of patient objects
 * @returns {string} - HTML string for payment form
 */
function getPaymentFormTemplate(lang, patients) {
    lang = lang || 'en';
    patients = patients || [];
    const today = new Date().toISOString().split('T')[0];
    
    const t = {
        en: {
            documentInfo: 'Document Information',
            refNo: 'Ref No',
            docDate: 'Doc Date',
            date: 'Date',
            dueDate: 'Due Date',
            patientInfo: 'Patient Information',
            patientName: 'Patient Name',
            invoiceId: 'Invoice ID',
            nextSchedule: 'Next Schedule',
            patientPhone: 'Patient Phone',
            paymentCalc: 'Payment Calculation',
            totalAmount: 'Total Amount',
            discountType: 'Discount Type',
            amount: 'Amount',
            percent: 'Percent (%)',
            discountValue: 'Discount Value',
            grandTotal: 'Grand Total',
            paidAmount: 'Paid Amount',
            remainingBalance: 'Remaining Balance',
            paymentDetails: 'Payment Details',
            method: 'Method',
            account: 'Account',
            currency: 'Currency',
            remark: 'Remark',
            selectPatient: 'Select Patient',
            select: 'Select',
            cash: 'Cash',
            card: 'Credit/Debit Card',
            bankTransfer: 'Bank Transfer',
            mobilePayment: 'Mobile Payment',
            check: 'Check',
            accountPlaceholder: 'Account number or name',
            additionalNotes: 'Additional notes',
            autoGenerated: 'Auto-generated',
            cancel: 'Cancel',
            receivePayment: 'Receive Payment'
        },
        kh: {
            documentInfo: 'ព័ត៌មានឯកសារ',
            refNo: 'លេខយោង',
            docDate: 'កាលបរិច្ឆេទឯកសារ',
            date: 'កាលបរិច្ឆេទ',
            dueDate: 'កាលបរិច្ឆេទកំណត់',
            patientInfo: 'ព័ត៌មានអ្នកជំងឺ',
            patientName: 'ឈ្មោះអ្នកជំងឺ',
            invoiceId: 'លេខវិក្កយបត្រ',
            nextSchedule: 'កាលវិភាគបន្ទាប់',
            patientPhone: 'ទូរស័ព្ទអ្នកជំងឺ',
            paymentCalc: 'ការគណនាទូទាត់',
            totalAmount: 'ចំនួនសរុប',
            discountType: 'ប្រភេទបញ្ចុះតម្លៃ',
            amount: 'ចំនួន',
            percent: 'ភាគរយ (%)',
            discountValue: 'តម្លៃបញ្ចុះតម្លៃ',
            grandTotal: 'សរុបចុងក្រោយ',
            paidAmount: 'ចំនួនទូទាត់',
            remainingBalance: 'សមតុល្យនៅសល់',
            paymentDetails: 'ព័ត៌មានការទូទាត់',
            method: 'វិធីសាស្ត្រ',
            account: 'គណនី',
            currency: 'រូបិយប័ណ្ណ',
            remark: 'កំណត់សំគាល់',
            selectPatient: 'ជ្រើសរើសអ្នកជំងឺ',
            select: 'ជ្រើសរើស',
            cash: 'សាច់ប្រាក់',
            card: 'កាត',
            bankTransfer: 'ផ្ទេរប្រាក់',
            mobilePayment: 'ទូទាត់ចល័ត',
            check: 'មូលប្បទានប័ត្រ',
            accountPlaceholder: 'លេខគណនីឬឈ្មោះ',
            additionalNotes: 'កំណត់ចំណាំបន្ថែម',
            autoGenerated: 'បង្កើតស្វ័យប្រវត្តិ',
            cancel: 'បោះបង់',
            receivePayment: 'ទទួលការទូទាត់'
        }
    };
    const txt = t[lang] || t.en;

    const patientOptions = patients.map(p => `<option value="${p.id}">${p.name}</option>`).join('');

    return `
        <form id="paymentForm" onsubmit="handlePaymentSubmit(event)">
            <!-- Document Information -->
            <div class="form-section">
                <div class="form-section-title">
                    <i class="fas fa-file-invoice"></i>
                    ${txt.documentInfo}
                </div>
                <div class="form-row">
                    <div class="form-group">
                        <label class="form-label">${txt.refNo}</label>
                        <input type="text" class="form-input" name="refNo" placeholder="REF-001">
                    </div>
                    <div class="form-group">
                        <label class="form-label">${txt.docDate} <span class="required">*</span></label>
                        <input type="date" class="form-input" name="docDate" value="${today}" required>
                    </div>
                </div>
                <div class="form-row">
                    <div class="form-group">
                        <label class="form-label">${txt.date} <span class="required">*</span></label>
                        <input type="date" class="form-input" name="date" value="${today}" required>
                    </div>
                    <div class="form-group">
                        <label class="form-label">${txt.dueDate}</label>
                        <input type="date" class="form-input" name="dueDate">
                    </div>
                </div>
            </div>

            <!-- Patient Information -->
            <div class="form-section">
                <div class="form-section-title">
                    <i class="fas fa-user"></i>
                    ${txt.patientInfo}
                </div>
                <div class="form-row">
                    <div class="form-group">
                        <label class="form-label">${txt.patientName} <span class="required">*</span></label>
                        <select class="form-select" name="patientId" id="paymentPatientSelect" required onchange="loadPatientInvoice()">
                            <option value="">--- ${txt.selectPatient} ---</option>
                            ${patientOptions}
                        </select>
                    </div>
                    <div class="form-group">
                        <label class="form-label">${txt.invoiceId}</label>
                        <input type="text" class="form-input" name="invoiceId" id="invoiceIdField" readonly style="background: #f3f4f6; cursor: not-allowed;" placeholder="${txt.autoGenerated}">
                    </div>
                </div>
                <div class="form-row">
                    <div class="form-group">
                        <label class="form-label">${txt.nextSchedule}</label>
                        <input type="date" class="form-input" name="nextSchedule">
                    </div>
                    <div class="form-group">
                        <label class="form-label">${txt.patientPhone}</label>
                        <input type="text" class="form-input" name="patientPhone" id="patientPhoneField" readonly style="background: #f3f4f6;">
                    </div>
                </div>
            </div>

            <!-- Payment Amounts -->
            <div class="form-section">
                <div class="form-section-title">
                    <i class="fas fa-calculator"></i>
                    ${txt.paymentCalc}
                </div>
                <div class="form-row">
                    <div class="form-group">
                        <label class="form-label">${txt.totalAmount} <span class="required">*</span></label>
                        <input type="number" class="form-input" name="totalAmount" id="totalAmount" step="0.01" min="0" required oninput="calculatePaymentTotals()">
                    </div>
                    <div class="form-group">
                        <label class="form-label">${txt.discountType}</label>
                        <select class="form-select" name="discountType" id="discountType" onchange="calculatePaymentTotals()">
                            <option value="amount">${txt.amount}</option>
                            <option value="percent">${txt.percent}</option>
                        </select>
                    </div>
                </div>
                <div class="form-row">
                    <div class="form-group">
                        <label class="form-label">${txt.discountValue}</label>
                        <input type="number" class="form-input" name="discountValue" id="discountValue" step="0.01" min="0" value="0" oninput="calculatePaymentTotals()">
                    </div>
                    <div class="form-group">
                        <label class="form-label">${txt.grandTotal} <span class="required">*</span></label>
                        <input type="number" class="form-input" name="grandTotal" id="grandTotal" step="0.01" readonly style="background: #f3f4f6; font-weight: 600;">
                    </div>
                </div>
                <div class="form-row">
                    <div class="form-group">
                        <label class="form-label">${txt.paidAmount} <span class="required">*</span></label>
                        <input type="number" class="form-input" name="paidAmount" id="paidAmount" step="0.01" min="0" required oninput="calculatePaymentTotals()">
                    </div>
                    <div class="form-group">
                        <label class="form-label">${txt.remainingBalance}</label>
                        <input type="number" class="form-input" name="remainingBalance" id="remainingBalance" step="0.01" readonly style="background: #f3f4f6; font-weight: 600; color: #dc2626;">
                    </div>
                </div>
            </div>

            <!-- Payment Method & Details -->
            <div class="form-section">
                <div class="form-section-title">
                    <i class="fas fa-credit-card"></i>
                    ${txt.paymentDetails}
                </div>
                <div class="form-row">
                    <div class="form-group">
                        <label class="form-label">${txt.method} <span class="required">*</span></label>
                        <select class="form-select" name="method" required>
                            <option value="">--- ${txt.select} ---</option>
                            <option value="cash">${txt.cash}</option>
                            <option value="card">${txt.card}</option>
                            <option value="bank-transfer">${txt.bankTransfer}</option>
                            <option value="mobile-payment">${txt.mobilePayment}</option>
                            <option value="check">${txt.check}</option>
                        </select>
                    </div>
                    <div class="form-group">
                        <label class="form-label">${txt.account}</label>
                        <input type="text" class="form-input" name="account" placeholder="${txt.accountPlaceholder}">
                    </div>
                </div>
                <div class="form-row">
                    <div class="form-group">
                        <label class="form-label">${txt.currency} <span class="required">*</span></label>
                        <select class="form-select" name="currency" required>
                            <option value="USD" selected>USD ($)</option>
                            <option value="KHR">KHR (៛)</option>
                            <option value="THB">THB (฿)</option>
                        </select>
                    </div>
                    <div class="form-group">
                        <label class="form-label">${txt.remark}</label>
                        <input type="text" class="form-input" name="remark" placeholder="${txt.additionalNotes}">
                    </div>
                </div>
            </div>
            
            <div class="form-actions">
                <button type="button" class="btn btn-secondary" onclick="closeSlidePanel()">
                    <i class="fas fa-times"></i>
                    ${txt.cancel}
                </button>
                <button type="submit" class="btn btn-primary">
                    <i class="fas fa-check-circle"></i>
                    ${txt.receivePayment}
                </button>
            </div>
        </form>
    `;
}
